# Generated by Django 5.1.6 on 2025-02-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='photo',
            field=models.ImageField(default=None, upload_to='lectures/photos/'),
            preserve_default=False,
        ),
    ]
