# Generated by Django 5.1.6 on 2025-02-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lecture_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='photo',
        ),
        migrations.AddField(
            model_name='lecture',
            name='file',
            field=models.FileField(default=None, upload_to='lectures/files/'),
            preserve_default=False,
        ),
    ]
