# Generated by Django 5.1.6 on 2025-02-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lecture_photo_lecture_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='lecture',
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
