# Generated by Django 5.1.6 on 2025-02-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_certificate_lecture_certificate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(blank=True, upload_to='lectures/files/'),
        ),
    ]
