# Generated by Django 5.1.6 on 2025-02-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_lecture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
