# Generated by Django 5.1.6 on 2025-02-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lectureattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectureattendance',
            unique_together={('user', 'lecture')},
        ),
    ]
