# Generated by Django 5.1.6 on 2025-02-23 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_lectureattendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureattendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendors', to='app.lecture'),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
