# Generated by Django 5.1.6 on 2025-02-26 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to='app.lecture'),
        ),
        migrations.AlterField(
            model_name='lectureattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
