# Generated by Django 5.1.6 on 2025-02-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_lecture_course'),
        ('app', '0014_auto_20250227_2148'),
    ]

    operations = [
    ]
